version: "3"

networks:
  lb: 
    driver:
      bridge

services:
# Web Server Container
  lb:
    restart: always
    build: .
    image: nginx-lb
    container_name: nginx-lb
    working_dir: /etc/nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./cert:/etc/cert
    networks:
      - lb
